# Purpose: Configure logrotate for PostgreSQL logs with dynamic user and group
# Author: Anilkumar Sonawane
# Date: April 28, 2025
# Version: 1.0
# Environment: Ansible deployment for PostgreSQL log rotation
# Description: Sets up logrotate to rotate PostgreSQL logs daily, retain 7 days,
#              compress old logs, and apply correct permissions using variables
#              from logrotate_config_deployment/logrotate_variables.yml.

---
- name: Create logrotate configuration for PostgreSQL
  copy:
    dest: /etc/logrotate.d/postgresql
    content: |
      {{ pg_log_dir }}/*.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          create 0640 {{ postgres_user }} {{ postgres_group }}
          postrotate
              /usr/bin/pkill -u {{ postgres_user }} -HUP || true
          endscript
      }
    owner: root
    group: root
    mode: '0644'
  notify: Test logrotate configuration

- name: Ensure PostgreSQL log directory exists and has correct permissions
  file:
    path: "{{ pg_root_dir }}"
    state: directory
    owner: "{{ postgres_user | default('postgres') }}"
    group: "{{ postgres_group | default('postgres') }}"
    mode: '0750'

- name: Ensure PostgreSQL log directory exists and has correct permissions
  file:
    path: "{{ pg_log_dir }}"
    state: directory
    owner: "{{ postgres_user | default('postgres') }}"
    group: "{{ postgres_group | default('postgres') }}"
    mode: '0750'

- name: Find existing log files in PostgreSQL log directory
  find:
    paths: "{{ pg_log_dir }}"
    patterns: "*.log"
    file_type: file
  register: log_files

- name: Ensure existing log files have correct permissions
  file:
    path: "{{ item.path }}"
    owner: "{{ postgres_user | default('postgres') }}"
    group: "{{ postgres_group | default('postgres') }}"
    mode: '0640'
  loop: "{{ log_files.files }}"
  when: log_files.matched > 0
